name: Report Specific Filter Issue From Popup Panel
body:
  - type: markdown
    value: "## Before creating a new issue"
    attributes:
      value: |
        To avoid burdening volunteers with invalid issues:
        
        - Do not use another content blocker along uBO.
            - You need to verify that the issue still occurs when using only uBO.
        - Using too many filter lists increases likelihood of filter issues on websites.
            - You may be asked to verify that the issue still occurs when using only default filter lists.

  - type: textarea
    attributes:
      label: URL address of the web page
      description: |
        Filled by uBO, leave it alone.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Category
      description: |
        Filled by uBO, leave it alone.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the issue
      description: |
        Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshot(s)
      description: |
        Screenshot(s) for **difficult to describe visual issues are mandatory**. 
        Post **links** instead of inline images for screenshots containing **adult material**.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Configuration
      description: |
        Filled by uBO, leave it alone.
    validations:
      required: true  
