name: Report Specific Filter Issue From Popup Panel
description: |
  Use this template when reporting filter issue from uBO's popup panel.
body:
  - type: markdown
    attributes:
      value: "## Before creating a new issue"
  - type: markdown
    attributes:
      value: |
        To avoid burdening **volunteers** with invalid issues:
        - Force an update of [your filter lists](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists).
            - The fix to an issue might already be in the latest version of the lists.
            - This is especially important for a new installation of uBO.
        - Using too many filter lists increases likelihood of filter issues on websites.
            - You may be asked to verify that the issue still occurs when using only [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png).

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: To avoid burdening **volunteers** with invalid, duplicate, or just too many issues, disrespecting these steps may result in your account being blocked on this repo.
      options:
        - label: I did not open more than three (3) issues today
          required: true
        - label: I verified that the issue has not already been reported
          required: true
        - label: I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
          required: true
        - label: I verified that the issue occurs without custom filter lists
          required: true
        - label: I am not using another content blocker beside uBO
          required: true

  - type: textarea
    attributes:
      label: URL address of the web page
      description: |
        Filled by uBO, leave it alone.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Category
      description: |
        Filled by uBO, leave it alone.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the issue
      description: |
        Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshot(s)
      description: |
        Screenshot(s) for **difficult to describe visual issues are mandatory**. 
        Post **links** instead of inline images for screenshots containing **adult material**.
      placeholder: You can just drag-and-drop an image here
    validations:
      required: false

  - type: textarea
    attributes:
      label: Configuration
      description: |
        Filled by uBO, leave it alone.
    validations:
      required: true  
