name: GitHub CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '43 * * * *'

jobs:
  publish:
    name: Publish lists
    runs-on: ubuntu-latest
    steps:
      - name: Clone uAssets
        uses: actions/checkout@v3
        with:
            ref: gh-pages
      - name: Copy files to gh-pages
        run: |
          tools/make-gh-pages.sh
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit
        run: |
          git add -u
          git commit -m "Update all lists"
          git push origin gh-pages
