name: GitHub CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '43 * * * *'

jobs:
  publish:
    name: Publish lists
    runs-on: ubuntu-latest
    steps:
      - name: Clone uAssets
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Copy to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tools/make-gh-pages.sh
